// config/entityDefinitions.js
export const entityDefinitions = {
  content_type: {
    table: 'content_type',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: true,
    createdField: 'created_at',
    updatedField: 'updated_at',
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      name: {
        type: 'VARCHAR',
        constraint: 100,
        null: false,
        unique: true,
        cast: 'string',
        validation: 'required|max_length[100]|is_unique[content_type.name]',
        label: 'Name',
        form: { type: 'text' },
      },
      label: {
        type: 'VARCHAR',
        constraint: 255,
        null: false,
        cast: 'string',
        validation: 'required|max_length[255]',
        label: 'Label',
        form: { type: 'text' },
      },
    },
    allowedFilters: ['name', 'label'],
    listColumns: ['id', 'name', 'label', 'created_at'],
    formFields: ['name', 'label'],
  },

  field_configs: {
    table: 'field_configs',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: true,
    createdField: 'created_at',
    updatedField: 'updated_at',
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_type_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Type',
        form: { type: 'select', source: 'content_type' },
      },
      name: {
        type: 'VARCHAR',
        constraint: 100,
        null: false,
        cast: 'string',
        validation: 'required|max_length[100]',
        label: 'Field Name',
        form: { type: 'text' },
      },
      label: {
        type: 'VARCHAR',
        constraint: 255,
        null: false,
        cast: 'string',
        validation: 'required|max_length[255]',
        label: 'Field Label',
        form: { type: 'text' },
      },
      storage_type: {
        type: 'VARCHAR',
        constraint: 20,
        null: false,
        cast: 'string',
        validation: 'required|in_list[text,integer,real,blob,reference]',
        label: 'Storage Type',
        form: { type: 'select', options: ['text', 'integer', 'real', 'blob', 'reference'] },
      },
      validation: {
        type: 'TEXT',
        null: true,
        cast: '?string',
        validation: 'permit_empty|string',
        label: 'Validation Rules',
        form: { type: 'textarea' },
      },
      filters: {
        type: 'TEXT',
        null: true,
        cast: '?string',
        validation: 'permit_empty|string',
        label: 'Filters',
        form: { type: 'textarea' },
      },
    },
    allowedFilters: ['content_type_id', 'name', 'storage_type'],
    listColumns: ['id', 'content_type_id', 'name', 'label', 'storage_type', 'created_at'],
    formFields: ['content_type_id', 'name', 'label', 'storage_type', 'validation', 'filters'],
    foreignKeys: {
      content_type_id: ['content_type', 'id'],
    },
  },

  content_data: {
    table: 'content_data',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: true,
    createdField: 'created_at',
    updatedField: 'updated_at',
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_type_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Type',
        form: { type: 'select', source: 'content_type' },
      },
    },
    allowedFilters: ['content_type_id'],
    listColumns: ['id', 'content_type_id', 'created_at'],
    formFields: ['content_type_id'],
    foreignKeys: {
      content_type_id: ['content_type', 'id'],
    },
  },

  field_value_text: {
    table: 'field_value_text',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: false,
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_data_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Data',
        form: { type: 'select', source: 'content_data' },
      },
      field_config_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Field Config',
        form: { type: 'select', source: 'field_configs' },
      },
      value: {
        type: 'TEXT',
        null: false,
        cast: 'string',
        validation: 'required|string',
        label: 'Value',
        form: { type: 'textarea' },
      },
    },
    allowedFilters: ['content_data_id', 'field_config_id'],
    listColumns: ['id', 'content_data_id', 'field_config_id', 'value'],
    formFields: ['content_data_id', 'field_config_id', 'value'],
    foreignKeys: {
      content_data_id: ['content_data', 'id'],
      field_config_id: ['field_configs', 'id'],
    },
  },

  field_value_integer: {
    table: 'field_value_integer',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: false,
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_data_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Data',
        form: { type: 'select', source: 'content_data' },
      },
      field_config_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Field Config',
        form: { type: 'select', source: 'field_configs' },
      },
      value: {
        type: 'INT',
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Value',
        form: { type: 'number' },
      },
    },
    allowedFilters: ['content_data_id', 'field_config_id'],
    listColumns: ['id', 'content_data_id', 'field_config_id', 'value'],
    formFields: ['content_data_id', 'field_config_id', 'value'],
    foreignKeys: {
      content_data_id: ['content_data', 'id'],
      field_config_id: ['field_configs', 'id'],
    },
  },

  field_value_real: {
    table: 'field_value_real',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: false,
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_data_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Data',
        form: { type: 'select', source: 'content_data' },
      },
      field_config_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Field Config',
        form: { type: 'select', source: 'field_configs' },
      },
      value: {
        type: 'DECIMAL',
        constraint: '12,6',
        null: false,
        cast: 'float',
        validation: 'required|decimal',
        label: 'Value',
        form: { type: 'number', step: 'any' },
      },
    },
    allowedFilters: ['content_data_id', 'field_config_id'],
    listColumns: ['id', 'content_data_id', 'field_config_id', 'value'],
    formFields: ['content_data_id', 'field_config_id', 'value'],
    foreignKeys: {
      content_data_id: ['content_data', 'id'],
      field_config_id: ['field_configs', 'id'],
    },
  },

  field_value_blob: {
    table: 'field_value_blob',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: false,
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_data_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Data',
        form: { type: 'select', source: 'content_data' },
      },
      field_config_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Field Config',
        form: { type: 'select', source: 'field_configs' },
      },
      value: {
        type: 'BLOB',
        null: false,
        cast: 'string',
        validation: 'required',
        label: 'Value',
        form: { type: 'text' },
      },
    },
    allowedFilters: ['content_data_id', 'field_config_id'],
    listColumns: ['id', 'content_data_id', 'field_config_id'],
    formFields: ['content_data_id', 'field_config_id', 'value'],
    foreignKeys: {
      content_data_id: ['content_data', 'id'],
      field_config_id: ['field_configs', 'id'],
    },
  },

  content_reference: {
    table: 'content_reference',
    primaryKey: 'id',
    compositeKey: false,
    useTimestamps: false,
    fields: {
      id: {
        type: 'INT',
        unsigned: true,
        auto: true,
        cast: 'integer',
        label: 'ID',
        form: { type: 'hidden' },
      },
      content_data_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Content Data',
        form: { type: 'select', source: 'content_data' },
      },
      field_config_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Field Config',
        form: { type: 'select', source: 'field_configs' },
      },
      referenced_content_id: {
        type: 'INT',
        unsigned: true,
        null: false,
        cast: 'integer',
        validation: 'required|integer',
        label: 'Referenced Content',
        form: { type: 'select', source: 'content_data' },
      },
    },
    allowedFilters: ['content_data_id', 'field_config_id', 'referenced_content_id'],
    listColumns: ['id', 'content_data_id', 'field_config_id', 'referenced_content_id'],
    formFields: ['content_data_id', 'field_config_id', 'referenced_content_id'],
    foreignKeys: {
      content_data_id: ['content_data', 'id'],
      field_config_id: ['field_configs', 'id'],
      referenced_content_id: ['content_data', 'id'],
    },
  },
};